package ua.com.model;


import ua.com.utils.IdAutoGenerated;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.List;

@Entity
@Table(name = "clans")
public class Clan extends IdAutoGenerated implements Serializable {

    @Column(name = "name")
    private String name;

    @OneToMany(mappedBy = "clan")
    List<Candidate> candidateList;

    public Clan() {
    }

    public Clan(String name, List<Candidate> candidateList) {
        this.name = name;
        this.candidateList = candidateList;
    }

    public Clan(String name) {
       this.name = name;
    }

    @Override
    public String toString() {
        return "Clan{" +
                "name='" + name + '\'' +
                '}';
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Candidate> getCandidateList() {
        return candidateList;
    }

    public void setCandidateList(List<Candidate> candidateList) {
        this.candidateList = candidateList;
    }
}
