package ua.com.model;


import ua.com.utils.IdAutoGenerated;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


@Entity
@Table(name = "regions")
public class Region extends IdAutoGenerated implements Serializable {

    @Column(name = "title")
    @Enumerated(EnumType.STRING)
    private RegionName title;

    @Column(name = "population")
    private long population;

    @OneToMany(mappedBy = "region")
    List<Candidate> candidates;

    public Region() {
    }

    public Region(RegionName title) {
        this.title = title;
    }

    public Region(RegionName title, long population) {
        this.title = title;
        this.population = population;
    }

    public Region(RegionName title, long population, List<Candidate> candidates) {
        this.title = title;
        this.population = population;
        this.candidates = candidates;
    }


    @Override
    public String toString() {
        return "Region{" +
                "title=" + title +
                ", population=" + population +
                ", candidates=" + candidates +
                '}';
    }

    public RegionName getTitle() {
        return title;
    }

    public void setTitle(RegionName title) {
        this.title = title;
    }

    public long getPopulation() {
        return population;
    }

    public void setPopulation(long population) {
        this.population = population;
    }

    public List<Candidate> getCandidates() {
        return candidates;
    }

    public void setCandidates(List<Candidate> candidates) {
        this.candidates = candidates;
    }
}
