
package ua.com.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CandidateEndpointImplService", targetNamespace = "http://soap.com.ua/", wsdlLocation = "http://localhost:9999/soap/eva?wsdl")
public class CandidateEndpointImplService
    extends Service
{

    private final static URL CANDIDATEENDPOINTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CANDIDATEENDPOINTIMPLSERVICE_EXCEPTION;
    private final static QName CANDIDATEENDPOINTIMPLSERVICE_QNAME = new QName("http://soap.com.ua/", "CandidateEndpointImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/soap/eva?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CANDIDATEENDPOINTIMPLSERVICE_WSDL_LOCATION = url;
        CANDIDATEENDPOINTIMPLSERVICE_EXCEPTION = e;
    }

    public CandidateEndpointImplService() {
        super(__getWsdlLocation(), CANDIDATEENDPOINTIMPLSERVICE_QNAME);
    }

    public CandidateEndpointImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CANDIDATEENDPOINTIMPLSERVICE_QNAME, features);
    }

    public CandidateEndpointImplService(URL wsdlLocation) {
        super(wsdlLocation, CANDIDATEENDPOINTIMPLSERVICE_QNAME);
    }

    public CandidateEndpointImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CANDIDATEENDPOINTIMPLSERVICE_QNAME, features);
    }

    public CandidateEndpointImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CandidateEndpointImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CandidateEndpoint
     */
    @WebEndpoint(name = "CandidateEndpointImplPort")
    public CandidateEndpoint getCandidateEndpointImplPort() {
        return super.getPort(new QName("http://soap.com.ua/", "CandidateEndpointImplPort"), CandidateEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CandidateEndpoint
     */
    @WebEndpoint(name = "CandidateEndpointImplPort")
    public CandidateEndpoint getCandidateEndpointImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.com.ua/", "CandidateEndpointImplPort"), CandidateEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CANDIDATEENDPOINTIMPLSERVICE_EXCEPTION!= null) {
            throw CANDIDATEENDPOINTIMPLSERVICE_EXCEPTION;
        }
        return CANDIDATEENDPOINTIMPLSERVICE_WSDL_LOCATION;
    }

}
