
package ua.com.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CandidateEndpoint", targetNamespace = "http://soap.com.ua/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CandidateEndpoint {


    /**
     * 
     * @param arg0
     * @return
     *     returns ua.com.soap.Candidate
     * @throws RegisterException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.com.ua/CandidateEndpoint/createCandidateRequest", output = "http://soap.com.ua/CandidateEndpoint/createCandidateResponse", fault = {
        @FaultAction(className = RegisterException_Exception.class, value = "http://soap.com.ua/CandidateEndpoint/createCandidate/Fault/RegisterException")
    })
    public Candidate createCandidate(
        @WebParam(name = "arg0", partName = "arg0")
        Candidate arg0)
        throws RegisterException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ua.com.soap.Candidate
     * @throws NoEntityFoundException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.com.ua/CandidateEndpoint/findCandidateRequest", output = "http://soap.com.ua/CandidateEndpoint/findCandidateResponse", fault = {
        @FaultAction(className = NoEntityFoundException_Exception.class, value = "http://soap.com.ua/CandidateEndpoint/findCandidate/Fault/NoEntityFoundException")
    })
    public Candidate findCandidate(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0)
        throws NoEntityFoundException_Exception
    ;

}
